import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="width-full flex flex-col justify-center items-center min-h-screen">

      <h1
        style={{ fontFamily: "Rock Salt, cursive", color: "#333" }}
        id="titulo"
        >
        Gracias Totales
      </h1>
    <div className="relative w-[60%] sm:w-[500px] h-[400px] bg-customGray rounded-md flex justify-center">
      <div className="w-[60%] min-h-full flex flex-col justify-center items-center">
        
        {children}
      </div>
    </div>
        </div>
  );
}
