
import { VerificationComponent } from "@/component/verificationComponent";
import { ClienSidebar } from "@/ui/components/navbar/ClientSidebar";
import { ClientTopNavbar } from "@/ui/components/navbar/ClientTopNavbar";
import type { Metadata } from "next";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashBoardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <div className="w-full">
            <VerificationComponent>
                <ClienSidebar />
                <ClientTopNavbar />
                {children}
            </VerificationComponent>

        </div>


    );
}
